### ISSUE TITLE
Dropbox Authentication - Asking for permissions again even after authentication

### ISSUE THREAD

**Issue by dexter1691** [batra-mlp-lab/CloudCV#13]

**Comment by dexter1691** [comment]
http://stackoverflow.com/questions/24531610/dropbox-api-on-android-always-asking-for-permission-to-link-app-to-dropbox-acco

@DESHRAJ: This might be helpful. You have to just find the right place in the social-auth code to add this.

**Comment by deshraj** [comment]
@dexter1691 This bug has been fixed in the workspaces branch. Closing it.
