### ISSUE TITLE
Write unit tests for all views

### ISSUE THREAD

**Issue by deshraj** [batra-mlp-lab/CloudCV#18]

**Comment by shivamMg** [comment]
@DESHRAJ Can I pick this up, if someone isn't working on it already.

**Comment by deshraj** [comment]
@shivamMg yeah sure you can. Just create a Pull request when you are done writing the tests and then we can review it.

**Comment by shivamMg** [comment]
Hey @DESHRAJ I think we should split this in smaller parts. There are too many views to write tests for and a lot of them are complex. I will make myself comfortable with the code, and work on other issues.

**Comment by dexter1691** [comment]
Miniconda, Caffe, OpenCV working on Travis-CI
Look at #29

**Comment by muddlebee** [comment]
@deshraj is anyone on this ? @gauthamzz and me can split the tasks and work on this ?

**Comment by deshraj** [comment]
@anweshknayak we are planning to rebuild the CloudCV website. So, we don't want to solve this issue now. We will let you once we have everything planned. :-)
