### ISSUE TITLE
`BooleanField` does not have a default value

### ISSUE THREAD

**Issue by shivamMg** [batra-mlp-lab/CloudCV#22]
After I issue the `migrate` command I get the following warning:

```
System check identified some issues:

WARNINGS:
app.CloudCV_Users.is_active: (1_6.W002) BooleanField does not have a default value.
    HINT: Django 1.6 changed the default value of BooleanField from False to None. See https://docs.djangoproject.com/en/1.6/ref/models/fields/#booleanfield for more information.
app.RequestLog.isDropbox: (1_6.W002) BooleanField does not have a default value.
    HINT: Django 1.6 changed the default value of BooleanField from False to None. See https://docs.djangoproject.com/en/1.6/ref/models/fields/#booleanfield for more information.
```

A fix would be to provide default values to `BooleanField`s.

**Comment by deshraj** [comment]
@shivamMg we have changed the database models but they are not merged in the master branch. We are still working on it. What you can do is write the tests for the current views and then we can modify the tests in future whenever we shift.

**Comment by deshraj** [comment]
:+1: Closing it.

**Comment by shivamMg** [comment]
@DESHRAJ Looks like I saw this a little late. Alright I'm going to write the tests then.
