### ISSUE TITLE
Upgrade django to version 1.9

### ISSUE THREAD

**Issue by deshraj** [batra-mlp-lab/CloudCV#28]

**Comment by Curious72** [comment]
@DESHRAJ  can i work on this ?

**Comment by deshraj** [comment]
@Curious72 yeah sure. Assigning it to you. :+1: 

EDIT: Cannot assign it to you since you are not a member. Just create a PR and I ll review and merge it.

**Comment by deshraj** [comment]
Issue fixed in #38 Django updated to latest version 1.10
