### ISSUE TITLE
Problem in setting up the local build! 

### ISSUE THREAD

**Issue by Curious72** [batra-mlp-lab/CloudCV#32]
I am having some problems while setting up the local build , I followed the documentation correctly , and the build is unable to import Caffe . 

![screenshot from 2016-03-26 23-56-49](https://cloud.githubusercontent.com/assets/8409274/14064510/7dfe8a90-f423-11e5-93b2-dfb977833d4f.png)

**Comment by deshraj** [comment]
@Curious72 there is some problem with the `cloudcv_worker_cpu` docker container. Its not running. Try running the `worker-cpu.sh` again and let us know if you get any problem.

**Comment by Curious72** [comment]
I ran worker-cpu.sh command and then run docker logs cloudcv_worker_cpu , i got following errors 
![screenshot from 2016-03-29 08-37-33](https://cloud.githubusercontent.com/assets/8409274/14114493/04ff7482-f58c-11e5-9d9e-143e4db3fd29.png)

RuntimeError: module compiled against API version a but this version of numpy is 9

**Comment by deshraj** [comment]
@Curious72 I have fixed this issue. Works fine on Ubuntu 14.04. Let me know if you have any other problem in setting up.
