### ISSUE TITLE
Issue with run_server on OSX

### ISSUE THREAD

**Issue by virajprabhu** [batra-mlp-lab/CloudCV#34]
Running run_server.sh fails on OSX, for a couple of reasons:

1) The -P flag needs to be passed to expose ports from the container to the localhost as explained [here](https://docs.docker.com/v1.8/installation/mac/).
2) With sudo applied, it fails with the error `Cannot connect to the Docker daemon. Is the docker daemon running on this host?` - not sure why this happens.

With both these fixed, it works fine (at the address of the default VM, not localhost). 

If CloudCV is supported on OSX, we should add Mac specific instructions in the README. I can submit a PR for this, if required.

**Comment by dexter1691** [comment]
@virajprabhu Thanks for trying it out. We haven't rigorously tested it on an osx machine but it would be great to do. You can submit a PR for this if you like. 

We have gh-pages branch which contains the sphinx documentation. May be you can add a section there. You can access the docs here : http://batra-mlp-lab.github.io/CloudCV/

**Comment by dexter1691** [comment]
> With sudo applied, it fails with the error Cannot connect to the Docker daemon. Is the docker daemon running on this host? - not sure why this happens

Not sure about this. I found a relevant issue that might be helpful:
http://stackoverflow.com/questions/36193300/mac-os-x-sudo-docker-cannot-connect-to-the-docker-daemon-is-the-docker-daemon-r

**Comment by virajprabhu** [comment]
I have already run `eval $(docker-machine env default)` to connect it to my shell, and confirmed that the default VM is up and running, but no luck. I have a default Docker installation, so I don't think it should be something related to my configuration. Without the sudo it doesn't throw an error though.

I'll submit a PR for Mac specific run instructions though, thanks.

**Comment by virajprabhu** [comment]
@dexter1691, is there any configuration that is required to run CloudCV from a fork? I'm getting a 500 when I try to run my fork locally. The base repo runs fine.

**Comment by dexter1691** [comment]
not sure. Do you have a log that I can look at?

**Comment by virajprabhu** [comment]
This is the nginx error log:
`2016/04/28 03:30:08 [error] 5#5: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.99.1, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://172.17.0.5:8000", host: "192.168.99.100"`
It seems to be an nginx configuration related error. Any ideas?

**Comment by virajprabhu** [comment]
Still haven't made any progress with this. @DESHRAJ , do you have any guesses for what might be going wrong? For context: I get a 500 Internal Server error on when I try to run CloudCV from my fork on OSX, but not when I clone and run the base repo. The nginx error log is mentioned in the comment above.

**Comment by abhshkdz** [comment]
@virajprabhu assuming you haven't made any local changes yet and your fork is up-to-date with the base repo, isn't the only difference b/w your fork and base the different git remotes?

**Comment by deshraj** [comment]
@virajprabhu can you please check the log of the `cloudcv_django` docker container so that we can know why you are getting 500 error ?

You can check the log using the command `docker logs cloudcv_django`. Let me know if the error is related to redis connection.

**Comment by virajprabhu** [comment]
@deshraj, the logs show a redis ConnectionError:

`Traceback (most recent call last):
  File "/CloudCV_Server/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 94, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/CloudCV_Server/cloudcv17/settings.py", line 133, in <module>
    r.set('CLOUDCV_ABS_DIR', BASE_ABS_DIR)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 1055, in set
    return self.execute_command('SET', *pieces)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 570, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 556, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 532, in send_packed_command
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 436, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 0.0.0.0:6379. Connection refused.
`
The redis config in `cloudcv17/settings.py` seems to be the issue?

@abhshkdz , ideally yes. But on OSX, the docker daemon runs inside a Linux VM with its own IP address and the ports on each container that's created are mapped to it, unlike on Linux where everything runs directly on localhost. I'm guessing that the error might be arising due to some issue with the mapping.

**Comment by deshraj** [comment]
@virajprabhu you just need to set `REDIS_HOST` as `localhost` in cloudcv17/config.py and then it should work fine.

**Comment by virajprabhu** [comment]
@DESHRAJ , I tried that but I still get the error. Also, turns out I didn't have the latest base repo. After pulling, I get the same error when I run the base repo too. 

The change of `REDIS_HOST` from `redis` to `0.0.0.0` seems to have broken it. I tried changing it back but that gives me a missing caffe dependency.

**Comment by virajprabhu** [comment]
@DESHRAJ, @dexter1691 , a couple more observations:
1) `server code changes tracked for a checkpoint` is causing the internal server error for me - I'm able to get it running from the commit before that. Since there are a lot of changes though, I'm not sure where to look.
2) `Fixing PEP8 issues`: some imports (for caffe etc.) were moved to the top of `trainTasks.py`. This will cause a missing caffe (and other) dependencies for anyone who runs `run_server` without running `worker-cpu` (which is mentioned as the last step in the README).

**Comment by virajprabhu** [comment]
@DESHRAJ , @dexter1691 : Can anyone verify if a fresh installation from scratch works with the latest code even on Linux? I get the same error when I try to run in an Ubuntu VM too.

**Comment by tocttou** [comment]
I tried a build on linux and got 500 Internal Server Error

**Comment by deshraj** [comment]
@virajprabhu i fixed the issue with the `cloudcv_worker_cpu` container. Now, this container is running successfully. You can see the code changes in the `dev` branch. But now there is an error of `caffe import`. I think its related to linking of docker containers. @dexter1691 can you help with this ?

**Comment by deshraj** [comment]
@virajprabhu can you try again setting up on OSx ? I have fixed the bug. Let me know if that still persists.

**Comment by deshraj** [comment]
Tested and working on OSx now.
