### ISSUE TITLE
Add `Grad-CAM` option to navigation bar of all pages

### ISSUE THREAD

**Issue by deshraj** [batra-mlp-lab/CloudCV#40]
A new element in the navigation bar list needs to be added on every page with name `Grad-CAM` that should point to the link http://gradcam.cloudcv.org

**Comment by RishabhJain2018** [comment]
@DESHRAJ  Can I work on this issue?

**Comment by deshraj** [comment]
@RishabhJain2018 Yeah Sure. Let us know if you need any help.

**Comment by RishabhJain2018** [comment]
@DESHRAJ ok sure.

**Comment by RishabhJain2018** [comment]
@DESHRAJ should the link be opened in a new tab?

**Comment by deshraj** [comment]
Yeah, the link should be opened in a new tab.
