### ISSUE TITLE
Integrate django-channels for showing realtime updates of Jobs

### ISSUE THREAD

**Issue by deshraj** [batra-mlp-lab/CloudCV#41]
We are planning to use Django-channels for showing the real-time updates on the terminal for Job Status. Also, Django-channels is going to be an integral part of Django after its 1.10 release.

For more details, see this :
- https://blog.heroku.com/in_deep_with_django_channels_the_future_of_real_time_apps_in_django
- https://channels.readthedocs.io/en/latest/

**Comment by RishabhJain2018** [comment]
@deshraj Can I work on this issue??

**Comment by deshraj** [comment]
Yeah sure. Let me know if you need more information about this feature. For your reference, you can refer   https://github.com/Cloud-CV/Grad-CAM. We are using Django-channels in that project to show the real-time updates on the terminal on CloudCV pages.

**Comment by deshraj** [comment]
Fixed. Closing now.
